| table_sql                                                                                                                                                                                                                                                                                                                                                                                                  |
| ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| CREATE TABLE academic_courses (course_code text, instructor_name text, exam_dates jsonb, id uuid NOT NULL, semester_id uuid NOT NULL, updated_at timestamp with time zone, created_at timestamp with time zone, course_type text, credits numeric(3,1), course_name text NOT NULL);                                                                                                                        |
| CREATE TABLE attendance_logs (subject_id uuid NOT NULL, updated_at timestamp with time zone, created_at timestamp with time zone, notes text, status attendance_status NOT NULL, id uuid NOT NULL, profile_id uuid NOT NULL, lecture_date date NOT NULL);                                                                                                                                                  |
| CREATE TABLE bot_sessions (created_at timestamp with time zone, errors_count integer, messages_processed integer, started_at timestamp with time zone NOT NULL, id uuid NOT NULL, ended_at timestamp with time zone, session_type text);                                                                                                                                                                   |
| CREATE TABLE grades (notes text, id uuid NOT NULL, profile_id uuid NOT NULL, subject_id uuid NOT NULL, grade_type grade_type NOT NULL, marks numeric(5,2), max_marks numeric(5,2), weightage numeric(5,2), assessed_date date, created_at timestamp with time zone, updated_at timestamp with time zone);                                                                                                  |
| CREATE TABLE message_queue (response_sent text, created_at timestamp with time zone, id uuid NOT NULL, whatsapp_number text, message_text text NOT NULL, received_at timestamp with time zone NOT NULL, processed boolean, processed_at timestamp with time zone);                                                                                                                                         |
| CREATE TABLE otp_codes (used boolean, created_at timestamp with time zone, attempts integer, last_sent_at timestamp with time zone, whatsapp_number text NOT NULL, code text NOT NULL, expires_at timestamp with time zone NOT NULL);                                                                                                                                                                      |
| CREATE TABLE profiles (timezone text NOT NULL, target_attendance_pct numeric(5,2), updated_at timestamp with time zone, created_at timestamp with time zone, current_semester_id uuid, current_program_id uuid, current_university_id uuid, personal_enabled boolean, academics_enabled boolean, email text, display_name text NOT NULL, whatsapp_number text NOT NULL, id uuid NOT NULL);                 |
| CREATE TABLE programs (default_target_attendance numeric(5,2), updated_at timestamp with time zone, created_at timestamp with time zone, duration_years numeric(3,1), total_semesters integer, degree_type text, name text NOT NULL, university_id uuid NOT NULL, id uuid NOT NULL);                                                                                                                       |
| CREATE TABLE semesters (updated_at timestamp with time zone, id uuid NOT NULL, created_at timestamp with time zone, name text NOT NULL, semester_number integer NOT NULL, program_id uuid NOT NULL);                                                                                                                                                                                                       |
| CREATE TABLE study_timers (notes text, id uuid NOT NULL, profile_id uuid NOT NULL, subject_id uuid NOT NULL, started_at timestamp with time zone NOT NULL, ended_at timestamp with time zone, duration_seconds integer, created_at timestamp with time zone, total_pause_seconds integer, pause_started_at timestamp with time zone);                                                                      |
| CREATE TABLE subject_categories (color_hex text, id uuid NOT NULL, is_default boolean, created_at timestamp with time zone, updated_at timestamp with time zone, profile_id uuid NOT NULL, name text NOT NULL);                                                                                                                                                                                            |
| CREATE TABLE subjects (source_course_id uuid, is_active boolean, color_hex text, description text, label text, type subject_type NOT NULL, profile_id uuid NOT NULL, id uuid NOT NULL, category_id uuid, expected_total_lectures integer, created_at timestamp with time zone, name text NOT NULL, legacy_attended_lectures integer, legacy_missed_lectures integer, updated_at timestamp with time zone); |
| CREATE TABLE tasks (priority task_priority, due_date timestamp with time zone, description text, title text NOT NULL, subject_id uuid, profile_id uuid NOT NULL, id uuid NOT NULL, completed_at timestamp with time zone, created_at timestamp with time zone, updated_at timestamp with time zone, has_reminder boolean, is_exam boolean, reminder_time timestamp with time zone, is_completed boolean);  |
| CREATE TABLE universities (country text, location text, name text NOT NULL, created_at timestamp with time zone, id uuid NOT NULL, updated_at timestamp with time zone);                                                                                                                                                                                                                                   |


| rls_enable                                                | rls_sql                                                                                                                                      |
| --------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- |
| ALTER TABLE subject_categories ENABLE ROW LEVEL SECURITY; | CREATE POLICY "Users can delete own categories" ON subject_categories FOR DELETE TO public USING ((profile_id = get_profile_id_from_jwt())); |
| ALTER TABLE subject_categories ENABLE ROW LEVEL SECURITY; | null                                                                                                                                         |
| ALTER TABLE subject_categories ENABLE ROW LEVEL SECURITY; | CREATE POLICY "Users can update own categories" ON subject_categories FOR UPDATE TO public USING ((profile_id = get_profile_id_from_jwt())); |
| ALTER TABLE subject_categories ENABLE ROW LEVEL SECURITY; | CREATE POLICY "Users can view own categories" ON subject_categories FOR SELECT TO public USING ((profile_id = get_profile_id_from_jwt()));   |
| ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;           | CREATE POLICY "Users can delete own subjects" ON subjects FOR DELETE TO public USING ((profile_id = get_profile_id_from_jwt()));             |
| ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;           | null                                                                                                                                         |
| ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;           | CREATE POLICY "Users can update own subjects" ON subjects FOR UPDATE TO public USING ((profile_id = get_profile_id_from_jwt()));             |
| ALTER TABLE subjects ENABLE ROW LEVEL SECURITY;           | CREATE POLICY "Users can view own subjects" ON subjects FOR SELECT TO public USING ((profile_id = get_profile_id_from_jwt()));               |
| ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;    | CREATE POLICY "Users can delete own attendance" ON attendance_logs FOR DELETE TO public USING ((profile_id = get_profile_id_from_jwt()));    |
| ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;    | null                                                                                                                                         |
| ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;    | CREATE POLICY "Users can update own attendance" ON attendance_logs FOR UPDATE TO public USING ((profile_id = get_profile_id_from_jwt()));    |
| ALTER TABLE attendance_logs ENABLE ROW LEVEL SECURITY;    | CREATE POLICY "Users can view own attendance" ON attendance_logs FOR SELECT TO public USING ((profile_id = get_profile_id_from_jwt()));      |
| ALTER TABLE grades ENABLE ROW LEVEL SECURITY;             | CREATE POLICY "Users can delete own grades" ON grades FOR DELETE TO public USING ((profile_id = get_profile_id_from_jwt()));                 |
| ALTER TABLE grades ENABLE ROW LEVEL SECURITY;             | null                                                                                                                                         |
| ALTER TABLE grades ENABLE ROW LEVEL SECURITY;             | CREATE POLICY "Users can update own grades" ON grades FOR UPDATE TO public USING ((profile_id = get_profile_id_from_jwt()));                 |
| ALTER TABLE grades ENABLE ROW LEVEL SECURITY;             | CREATE POLICY "Users can view own grades" ON grades FOR SELECT TO public USING ((profile_id = get_profile_id_from_jwt()));                   |
| ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;              | CREATE POLICY "Users can delete own tasks" ON tasks FOR DELETE TO public USING ((profile_id = get_profile_id_from_jwt()));                   |
| ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;              | null                                                                                                                                         |
| ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;              | CREATE POLICY "Users can update own tasks" ON tasks FOR UPDATE TO public USING ((profile_id = get_profile_id_from_jwt()));                   |
| ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;              | CREATE POLICY "Users can view own tasks" ON tasks FOR SELECT TO public USING ((profile_id = get_profile_id_from_jwt()));                     |
| ALTER TABLE study_timers ENABLE ROW LEVEL SECURITY;       | CREATE POLICY "Users can delete own timers" ON study_timers FOR DELETE TO public USING ((profile_id = get_profile_id_from_jwt()));           |
| ALTER TABLE study_timers ENABLE ROW LEVEL SECURITY;       | null                                                                                                                                         |
| ALTER TABLE study_timers ENABLE ROW LEVEL SECURITY;       | CREATE POLICY "Users can update own timers" ON study_timers FOR UPDATE TO public USING ((profile_id = get_profile_id_from_jwt()));           |
| ALTER TABLE study_timers ENABLE ROW LEVEL SECURITY;       | CREATE POLICY "Users can view own timers" ON study_timers FOR SELECT TO public USING ((profile_id = get_profile_id_from_jwt()));             |
| ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;           | CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE TO public USING ((id = get_profile_id_from_jwt()));                      |
| ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;           | CREATE POLICY "Users can view own profile" ON profiles FOR SELECT TO public USING ((id = get_profile_id_from_jwt()));                        |



| enum_sql                                                                                                        |
| --------------------------------------------------------------------------------------------------------------- |
| CREATE TYPE attendance_status AS ENUM ('present', 'absent', 'cancelled', 'deemed');                             |
| CREATE TYPE grade_type AS ENUM ('mid_sem', 'end_sem', 'viva', 'project', 'presentation', 'assignment', 'quiz'); |
| CREATE TYPE subject_type AS ENUM ('academic', 'personal');                                                      |
| CREATE TYPE task_priority AS ENUM ('low', 'medium', 'high', 'urgent');                                          |